### ISSUE TITLE
java.lang.ArithmeticException

### ISSUE THREAD

**Issue by oduysmara** [amalChandran/trail-android#33]
java.lang.ArithmeticException - divide by zero
Fatal Exception: java.lang.ArithmeticException: divide by zero
       at com.amalbit.trail.RouteOverlayView.calculateDimensionForDebugGrid(RouteOverlayView.java:25)
       at com.amalbit.trail.RouteOverlayView.onSizeChanged(RouteOverlayView.java:25)
       at android.view.View.sizeChange(View.java:23773)
       at android.view.View.setFrame(View.java:23725)
       at android.view.View.layout(View.java:23577)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:389)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:389)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:46)
       at android.view.View.layout(View.java:23580)
       at android.view.ViewGroup.layout(ViewGroup.java:6647)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
       at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1846)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1612)
       at android.view.View.layout(View.java:23580)
       at android.view.ViewGroup.layout(ViewGroup.java:6647)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:389)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:389)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:46)
       at android.view.View.layout(View.java:23580)
       at android.view.ViewGroup.layout(ViewGroup.java:6647)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23580)
       at android.view.ViewGroup.layout(ViewGroup.java:6647)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
       at android.view.View.layout(View.java:23580)
       at android.view.ViewGroup.layout(ViewGroup.java:6647)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23580)
       at android.view.ViewGroup.layout(ViewGroup.java:6647)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
       at android.view.View.layout(View.java:23580)
       at android.view.ViewGroup.layout(ViewGroup.java:6647)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:1141)
       at android.view.View.layout(View.java:23580)
       at android.view.ViewGroup.layout(ViewGroup.java:6647)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4869)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4251)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2828)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10506)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1623)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1141)
       at android.view.Choreographer.doFrame(Choreographer.java:1012)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1585)
       at android.os.Handler.handleCallback(Handler.java:955)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loopOnce(Looper.java:206)
       at android.os.Looper.loop(Looper.java:296)
       at android.app.ActivityThread.main(ActivityThread.java:8971)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
       at com.android.internal.os.ZygoteInit

**Comment by Menaitech** [comment]
any update please
